# Generated by Django 5.1.4 on 2025-03-04 09:07

import django.db.models.deletion
import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('folders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articoli',
            fields=[
                ('id', models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('titolo', models.CharField(max_length=255, verbose_name='Title')),
                ('autore', models.CharField(max_length=255, verbose_name='Author')),
                ('anno', models.PositiveIntegerField(verbose_name='Year')),
                ('fonte', models.CharField(max_length=255, verbose_name='Source Title')),
                ('citazioni', models.PositiveIntegerField(default=0, verbose_name='Cited by')),
                ('tipo_documento', models.CharField(max_length=50, verbose_name='Document Type')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Testo della Ricerca')),
                ('status', models.CharField(choices=[('Preso', 'Preso'), ('Scartato', 'Scartato')], default='Scartato', max_length=20)),
                ('lingua', models.CharField(choices=[('IT', 'Italian'), ('EN', 'English'), ('FR', 'French'), ('ES', 'Spanish'), ('DE', 'German')], default='EN', max_length=2, verbose_name='Lingua')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articoli', to='folders.folder')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('titolo', 'folder'), name='unique_research_per_folder')],
            },
        ),
    ]
