# Generated by Django 5.1.4 on 2025-03-06 16:21

import django.db.models.deletion
import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articoli', '0007_alter_articoli_id'),
        ('folders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articoli',
            name='id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='RicercaSalvata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salvato_il', models.DateTimeField(auto_now_add=True)),
                ('articolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articoli.articoli')),
                ('cartella', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='folders.folder')),
            ],
            options={
                'unique_together': {('cartella', 'articolo')},
            },
        ),
    ]
