# Generated by Django 5.1.4 on 2025-03-07 08:15

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articoli', '0009_alter_articoli_id'),
        ('folders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ricercasalvata',
            old_name='cartella',
            new_name='folder',
        ),
        migrations.AlterField(
            model_name='articoli',
            name='id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='ricercasalvata',
            unique_together={('folder', 'articolo')},
        ),
    ]
