# Generated by Django 5.1.4 on 2025-03-10 10:11

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articoli', '0014_alter_articoli_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articoli',
            name='anno',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='articoli',
            name='id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, primary_key=True, serialize=False),
        ),
    ]
