# Generated by Django 5.1.4 on 2025-03-10 14:35

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articoli', '0016_alter_articoli_id_alter_articoli_lingua'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articoli',
            name='id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='articoli',
            name='lingua',
            field=models.CharField(choices=[('IT', 'Italian'), ('EN', 'English'), ('FR', 'French'), ('ES', 'Spanish'), ('DE', 'German'), ('LT', 'Lituan'), ('JP', 'Japanese'), ('CH', 'Chinese'), ('RU', 'Russian')], default='EN', max_length=2, verbose_name='Lingua'),
        ),
    ]
